name: Package & Publish Release Asset

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.0

jobs:
  package:
    runs-on: windows-latest

    steps:
      # 1️⃣ Check out your code (including published/)
      - name: Checkout source
        uses: actions/checkout@v3

      # 2️⃣ Debug: list contents of published/
      - name: List published folder (debug)
        shell: pwsh
        run: |
          Write-Host "=== Contents of published/ ==="
          Get-ChildItem -Recurse published || Write-Host "No published folder found!"

      # 3️⃣ Zip your published/ folder
      - name: Create ZIP of published folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path release -Force | Out-Null
          Compress-Archive -Path .\published\* -DestinationPath .\release\${{ github.ref_name }}.zip -Force

      # 4️⃣ Create (or update) the GitHub Release for this tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5️⃣ Upload that ZIP as the asset
      - name: Upload ZIP asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release/${{ github.ref_name }}.zip
